# Generated by Django 5.1.7 on 2026-07-31 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CateringRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
                ('event_type', models.CharField(choices=[('wedding', 'Wedding'), ('corporate', 'Corporate'), ('birthday', 'Birthday'), ('other', 'Other')], default='wedding', max_length=20)),
                ('guest_count', models.PositiveIntegerField()),
                ('event_date', models.DateField()),
                ('venue_area', models.CharField(blank=True, max_length=120)),
                ('menu_ideas', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('quoted', 'Quoted'), ('won', 'Won'), ('lost', 'Lost')], db_index=True, default='new', max_length=20)),
            ],
            options={
                'verbose_name': 'catering request',
                'verbose_name_plural': 'catering requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('subject', models.CharField(choices=[('general', 'General enquiry'), ('order_issue', 'Order issue'), ('catering', 'Catering'), ('partnership', 'Partnership')], default='general', max_length=20)),
                ('message', models.TextField()),
                ('is_handled', models.BooleanField(default=False, help_text='Tick once someone has replied to this message.')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
