# Generated by Django 5.1.7 on 2026-09-25 11:10

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


def seed_packages(apps, schema_editor):
    """The three price cards that used to be typed into the catering template."""
    CateringPackage = apps.get_model("pages", "CateringPackage")
    if CateringPackage.objects.exists():
        return
    for order, (name, blurb, price) in enumerate([
        ("Weddings", "Traditional and white — plated or buffet service with a dedicated event lead.", "6500.00"),
        ("Corporate", "Conferences, office lunches and retreats with invoicing and scheduled drops.", "4800.00"),
        ("Private parties", "Birthdays, naming ceremonies, house parties. Small chops and grills included.", "5200.00"),
    ]):
        CateringPackage.objects.create(
            name=name, description=blurb, price_per_plate=price,
            minimum_guests=50, display_order=order,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CateringPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=80)),
                ('description', models.CharField(blank=True, max_length=220)),
                ('price_per_plate', models.DecimalField(decimal_places=2, help_text='Starting price per plate, in Naira.', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('minimum_guests', models.PositiveIntegerField(default=50, help_text='Smallest event this price applies to.')),
                ('display_order', models.PositiveSmallIntegerField(default=0, help_text='Lower numbers appear first.')),
                ('is_active', models.BooleanField(default=True, help_text='Untick to hide from the catering page.')),
            ],
            options={
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.RunPython(seed_packages, migrations.RunPython.noop),
    ]
