# Generated by Django 5.1.7 on 2026-09-25 11:10

from django.db import migrations, models


def keep_existing_addresses(apps, schema_editor):
    """Profiles saved before the breakdown only have one free-text address. Move it
    into the street field so nothing is lost; the customer is asked for city and
    state (is_complete needs them) the next time they check out."""
    Profile = apps.get_model("accounts", "Profile")
    for profile in Profile.objects.filter(address_line="").exclude(delivery_address=""):
        profile.address_line = profile.delivery_address.strip()[:200]
        profile.save(update_fields=["address_line"])


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='address_line',
            field=models.CharField(blank=True, help_text='House or flat number and street, e.g. 12 Admiralty Way.', max_length=200, verbose_name='Street address'),
        ),
        migrations.AddField(
            model_name='profile',
            name='area',
            field=models.CharField(blank=True, help_text='e.g. Lekki Phase 1, Yaba, Ikeja GRA.', max_length=100, verbose_name='Area / neighbourhood'),
        ),
        migrations.AddField(
            model_name='profile',
            name='city',
            field=models.CharField(blank=True, max_length=80, verbose_name='City / town'),
        ),
        migrations.AddField(
            model_name='profile',
            name='landmark',
            field=models.CharField(blank=True, help_text='Optional, but it saves the rider a phone call: gate colour, a bus stop, a shop.', max_length=150, verbose_name='Nearest landmark or rider directions'),
        ),
        migrations.AddField(
            model_name='profile',
            name='state',
            field=models.CharField(blank=True, choices=[('Abia', 'Abia'), ('Adamawa', 'Adamawa'), ('Akwa Ibom', 'Akwa Ibom'), ('Anambra', 'Anambra'), ('Bauchi', 'Bauchi'), ('Bayelsa', 'Bayelsa'), ('Benue', 'Benue'), ('Borno', 'Borno'), ('Cross River', 'Cross River'), ('Delta', 'Delta'), ('Ebonyi', 'Ebonyi'), ('Edo', 'Edo'), ('Ekiti', 'Ekiti'), ('Enugu', 'Enugu'), ('FCT (Abuja)', 'FCT (Abuja)'), ('Gombe', 'Gombe'), ('Imo', 'Imo'), ('Jigawa', 'Jigawa'), ('Kaduna', 'Kaduna'), ('Kano', 'Kano'), ('Katsina', 'Katsina'), ('Kebbi', 'Kebbi'), ('Kogi', 'Kogi'), ('Kwara', 'Kwara'), ('Lagos', 'Lagos'), ('Nasarawa', 'Nasarawa'), ('Niger', 'Niger'), ('Ogun', 'Ogun'), ('Ondo', 'Ondo'), ('Osun', 'Osun'), ('Oyo', 'Oyo'), ('Plateau', 'Plateau'), ('Rivers', 'Rivers'), ('Sokoto', 'Sokoto'), ('Taraba', 'Taraba'), ('Yobe', 'Yobe'), ('Zamfara', 'Zamfara')], max_length=40),
        ),
        migrations.AlterField(
            model_name='profile',
            name='delivery_address',
            field=models.TextField(blank=True, editable=False),
        ),
        migrations.RunPython(keep_existing_addresses, migrations.RunPython.noop),
    ]
